on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
  push:
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        lambdapi-version: [lambdapi.2.0.0, lambdapi.2.1.0, lambdapi.2.2.0, lambdapi]
    runs-on: ubuntu-latest
    steps:
      - name: Check out library
        uses: actions/checkout@v2
      - name: Install ocaml and opam
        uses: ocaml/setup-ocaml@v2
      - name: Setup opam for testing the development version
        run: opam pin -n --dev-repo lambdapi
        if: matrix.lambdapi-version == 'lambdapi'
      - name: Install ${{ matrix.lambdapi-version }}
        run: opam install ${{ matrix.lambdapi-version }}
      - name: Check library
        run: |
          eval $(opam env)
          make
