on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        lambdapi-version: [dev]

    runs-on: ubuntu-latest

    steps:
      - name: Check out library
        uses: actions/checkout@v7

      - name: Install ocaml and opam
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.5
          opam-repositories: |
            default: https://github.com/ocaml/opam-repository.git
            lambdapi: https://github.com/deducteam/opam-lambdapi-repository.git

      - name: Install lambdapi.${{ matrix.lambdapi-version }}
        run: opam install lambdapi.${{ matrix.lambdapi-version }}
        if: matrix.lambdapi-version != 'dev'

      - name: Install lambdapi development version
        run: |
          opam pin -n --dev-repo lambdapi
          opam install lambdapi
        if: matrix.lambdapi-version == 'dev'

      - name: Check library
        run: |
          eval $(opam env)
          make
